name: ml-projects
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # Core ML libraries
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  # Computer Vision
  - opencv>=4.8.0
  - pillow>=10.0.0
  # Development tools
  - jupyter
  - ipykernel
  - pip
  - pip:
    # Reinforcement Learning
    - gymnasium>=0.29.0
    - stable-baselines3>=2.0.0
    # Monitoring & Logging
    - tensorboard>=2.13.0
    - wandb
    # NLP
    - transformers>=4.30.0
    - tokenizers>=0.13.0
    # Additional ML utilities
    - tqdm>=4.65.0